Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    bridge_iface = "Realtek PCIe GbE Family Controller"
    default_memory = 2048
    default_cpu = 2

    vms = [
    {
    name: "vm1",
    hostname: "fast-lab-vm1",
    ip: "192.168.0.120",
    vb_name: "lab-vm1",
    },
    # {
    # name: "vm2",
    # hostname: "fast-lab-vm2",
    # ip: "192.168.0.121",
    # vb_name: "lab-vm2",
    # memory: 1024,
    # cpu: 3
    # }
    ]

vms.each do |vm_conf|
    config.vm.define vm_conf[:name] do |vm|
      vm.vm.hostname = vm_conf[:hostname]
      vm.vm.network "public_network",
        bridge: bridge_iface,
        ip: vm_conf[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name = vm_conf[:vb_name]
        vb.memory = vm_conf.fetch(:memory, default_memory)
        vb.cpus = vm_conf.fetch(:cpu, default_cpu)
      end

      config.vm.synced_folder "../docker/app", "/home/vagrant/app",
        owner: "vagrant", group: "vagrant"


      config.vm.provision "shell",
        privileged: true,
        path: "provision/nginx.sh",
        run: "once"

        # vm.vm.synced_folder "../docker", "/mnt/docker"
    end
  end   
end